blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions and Help
    url: 
    about: Reach out to us on discord or our github discussions page.
  - name: ğŸ“ Dedicated Support
    url: 
    about: Write to us if you'd like dedicated support 
